// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqadksqsoddegadylwtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xYWRrc3Fzb2RkZWdhZHlsd3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDM0MTksImV4cCI6MjA2OTk3OTQxOX0.uHU1EjyvbUUvVtnWOPlTaB7_ZRb0CPqBUQB74k4Hn0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});